# BiomeRemap
# This file must contain valid YAML code. A YAML checker may be found at http://www.yamllint.com
#
# Remap biomes to create strange new worlds.
#
# Design: SlimeDog
# Implementation: drives_a_ford
# Testing: SlimeDog
#
# Minecraft version support:
#   BiomeRemap 1.0.1    Spigot 1.14.4     
#   BiomeRemap 2.0.3    Spigot 1.15.2     
#   BiomeRemap 2.2.1    Spigot and Paper 1.16.5     
#   BiomeRemap 2.3.2    Spigot and Paper 1.17.1
#   BiomeRemap 3.0.0    Spigot and Paper 1.18
#
# This configuration file is compatible with Minecraft 1.18 only. Versions for previous Minecraft
# versions may be found at https://github.com/SlimeDog/BiomeRemap/wiki/Configuration.
#
# ========== CAVEATS AND WARNINGS ==================================================================
# BiomeRemap is provided for your enjoyment and entertainment. We cannot guarantee that the results
# will meet your needs or desires.
#
# The most important caveat: BIOME REMAPPING CANNOT BE REVERSED. Always backup the server before
# using this plugin, and test the functionality before you use it on a production server.
#
# BiomeRemap augments terrain generation by remapping biomes in the configured worlds as chunks are
# generated. Remapping previously generated chunks carries negative performance impacts and other
# potential risks. (For example, the underlying chunk populator may change, which could result in
# mismatched chunk or biome borders.) Consequently, BiomeRemap will not remap existing chunks
# automatically, even if the configuration is changed. They can be remapped manually, if desired.
# Commands to do so are described in the wiki.
#
# Due to the way MC world creation and chunk generation work, BiomeRemap does not automatically
# remap the chunks initially generated on world creation. These chunks must be remapped manually.
# Commands to do so are described in the wiki.
#
# Changes of this magnitude should always be performed first on a test server, in order to verify
# that the configuration and results meet expectations. We strongly recommend making a server backup
# before installing and using any new plugin.

# ========== CONFIGURATION FILE VERSION ============================================================
# This configuration file is compatible with Minecraft 1.18 only. Versions for previous Minecraft
# versions may be found at https://github.com/SlimeDog/BiomeRemap/wiki/Configuration.
#
# In Minecraft 1.18, 13 biomes were renamed, 25 biomes were deleted, and six new biomes were
# introduced. See https://github.com/SlimeDog/BiomeRemap/wiki/ for details.
#
# Biomes that do not exist in your Minecraft version will generate errors in the console/log,
# and BiomeRemap will fail to enable.
#
# Do not edit the version string unless you know what you are dolng.
file: config.yml
version: 1.18

# ========== CHECK FOR UPDATES =====================================================================
# If you do not want notification of available updates in the console log, you may disable it here.
check-for-updates: true

# ========== BSTATS METRICS ========================================================================
# By default, the plugin collects and transmits anonymous statistics to bstats.org.
# Data collection may be disabled here, or generally in the bStats/config.yml.
#
enable-metrics: true

# ========== BIOMEMAP CONFIGURATION ================================================================
# The main configuration is a list of biomemaps, enabled in specific world(s).
# Each biomemap contains a list of assigned worlds, and a list of biomes with replacement-biomes.
#
# biomemaps:
#   NAME:
#     description: TEXT
#     enabled-worlds: LIST
#     full-chunk-remap: true|false (default:false)
#     biomes:
#        BIOME_ENUM:
#         replacement-biome: BIOME_ENUM
#
# biomemaps.NAME
#   * required, unique
#   * identifies a biomemap
#   * multiple biomemaps may be defined, and subsets of worlds assigned to them
#   * snowbound and boilerroom sample biomemaps are included in the default configuration
# biomemaps.NAME.description
#   * optional, for reference only
# biomemaps.NAME.enabled-worlds
#   * required, a list of assigned worlds
#   * a world may be assigned to more than one biomemap, if you understand the consequences
#   * may be the empty set [] if no worlds are assigned
#   * overlapping combinations of worlds and biomes will generate non-fatal warnings in the console/log
# biomemaps.NAME.full-chunk-remap
#   * Prior to MC 1.16.2, "chunk" referred to a 16x16 column, across all Y values; the biome of the
#     entire column was specified by a single BIOME_ENUM value in the base chunk (Y=0).
#   * Starting with MC 1.16.2, "chunk" refers to a 16x16x16 cube; the biome of each cubic chunk may
#     be specified independently. BiomeRemap addresses this change in the following way:
#        * biomemaps.NAME.full-chunk-remap: false (default)
#          Only the base chunk (Y=0) will be remapped. This changes weather (for example, rain vs.
#          snow) in the entire column, but changes the visual characteristics (for example, grass
#          color) in the base chunk only. So the surface terrain characteristics remain unchanged.
#        * biomemaps.NAME.full-chunk-remap: true
#          The entire column will be remapped. This changes weather in the same way, but changes the
#          the visual characteristics of the entire column, so the surface terrain characteristics
#          will reflect the new biome. This will incur a small additional computational cost to loop
#          through the entire column, but it should not be noticeable in practice, and will not affect
#          game play if the chunks are pre-generated (which we recommend in any event).
#   * WARNING: The configuration should be changed only after careful consideration and testing. The
#     consequences of TRUE cannot be reversed, except by regenerating chunks after reverting to FALSE.
# biomemaps.NAME.biomes.BIOME_ENUM
#   * Required, unique per biomemap
#   * Identifies the vanilla biome that will be replaced
#   * An invalid biome ENUM will generate a non-fatal warning in the console/log
#   * Valid biome ENUMs may be found at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html
#     but we use lowercase, which may be found at https://minecraft.fandom.com/wiki/Biome
#   * Biome descriptions may be found at https://minecraft.fandom.com/wiki/Biome
#   * Additional information may be found at https://github.com/SlimeDog/BiomeRemap/wiki/
# biomemaps.NAME.biomes.BIOME_ENUM.replacement-biome
#   * Optional
#   * If present, defines the replacement biome
#   * If replacement is not defined for any biome, the biome will not be replaced
#   * An invalid biome ENUM will generate a non-fatal warning in the console/log, and revert to the named biome
#
# Other configuration nodes may be added, as usage warrants.

biomemaps:
  # ======== BiomeRemap example: snowbound ===========================================================
  # The climate has turned very cold. The entire world is covered with ice and snow.
  # Map every biome to a colder biome.
  #
  # enabled-worlds must be changed to reflect your target worlds.
  #
  snowbound:
    description: "The world is cold and icy. Snow everywhere."
    enabled-worlds:
      - world_name_goes_here
    biomes:
      badlands:
        replacement-biome: snowy_plains
      bamboo_jungle:
        replacement-biome: snowy_taiga
      beach:
        replacement-biome: snowy_beach
      birch_forest:
        replacement-biome: snowy_plains
      cold_ocean:
        replacement-biome: frozen_ocean
      dark_forest:
        replacement-biome: snowy_plains
      deep_cold_ocean:
        replacement-biome: frozen_ocean
      deep_frozen_ocean:
        replacement-biome: frozen_ocean
      deep_lukewarm_ocean:
        replacement-biome: frozen_ocean
      deep_ocean:
        replacement-biome: frozen_ocean
      desert:
        replacement-biome: snowy_plains
      dripstone_caves:
        replacement-biome: snowy_plains
      eroded_badlands:
        replacement-biome: snowy_slopes
      flower_forest:
        replacement-biome: snowy_plains
      forest:
        replacement-biome: snowy_plains
      frozen_ocean:
        replacement-biome: frozen_ocean
      frozen_peaks:
        replacement-biome: frozen_peaks
      frozen_river:
        replacement-biome: frozen_river
      grove:
        replacement-biome: grove
      ice_spikes:
        replacement-biome: ice_spikes
      jagged_peaks:
        replacement-biome: frozen_peaks
      jungle:
        replacement-biome: snowy_plains
      lukewarm_ocean:
        replacement-biome: frozen_ocean
      lush_caves:
        replacement-biome: snowy_plains
      meadow:
        replacement-biome: snowy_plains
      mushroom_fields:
        replacement-biome: snowy_plains
      ocean:
        replacement-biome: frozen_ocean
      old_growth_birch_forest:
        replacement-biome: snowy_plains
      old_growth_pine_taiga:
        replacement-biome: snowy_taiga
      old_growth_spruce_taiga:
        replacement-biome: snowy_taiga
      plains:
        replacement-biome: snowy_plains
      river:
        replacement-biome: frozen_river
      savanna:
        replacement-biome: snowy_plains
      savanna_plateau:
        replacement-biome: snowy_plains
      snowy_beach:
        replacement-biome: snowy_beach
      snowy_plains:
        replacement-biome: snowy_plains
      snowy_slopes:
        replacement-biome: snowy_slopes
      snowy_taiga:
        replacement-biome: snowy_taiga
      sparse_jungle:
        replacement-biome: snowy_plains
      stony_peaks:
        replacement-biome: snowy_slopes
      stony_shore:
        replacement-biome: snowy_beach
      sunflower_plains:
        replacement-biome: snowy_plains
      swamp:
        replacement-biome: snowy_plains
      taiga:
        replacement-biome: snowy_taiga
      warm_ocean:
        replacement-biome: frozen_ocean
      windswept_forest:
        replacement-biome: snowy_slopes
      windswept_gravelly_hills:
        replacement-biome: snowy_slopes
      windswept_hills:
        replacement-biome: snowy_slopes
      windswept_savanna:
        replacement-biome: snowy_plains
      wooded_badlands:
        replacement-biome: snowy_plains

  # ======== BiomeRemap example: boilerroom ==========================================================
  # Climate change is real. The entire world is warm, warmer, hot, hotter.
  # Map every biome to a warmer biome.
  #
  # enabled-worlds must be changed to reflect your target worlds.
  #
  boilerroom:
    description: "Climate change is real. The entire world is warm, warmer, hot, hotter."
    enabled-worlds: []
    biomes:
      badlands:
        replacement-biome: badlands
      bamboo_jungle:
        replacement-biome: bamboo_jungle
      beach:
        replacement-biome: desert
      birch_forest:
        replacement-biome: birch_forest
      cold_ocean:
        replacement-biome: warm_ocean
      dark_forest:
        replacement-biome: dark_forest
      deep_cold_ocean:
        replacement-biome: deep_lukewarm_ocean
      deep_frozen_ocean:
        replacement-biome: deep_lukewarm_ocean
      deep_lukewarm_ocean:
        replacement-biome: deep_lukewarm_ocean
      deep_ocean:
        replacement-biome: deep_lukewarm_ocean
      desert:
        replacement-biome: desert
      dripstone_caves:
        replacement-biome: dripstone_caves
      eroded_badlands:
        replacement-biome: eroded_badlands
      flower_forest:
        replacement-biome: flower_forest
      forest:
        replacement-biome: forest
      frozen_ocean:
        replacement-biome: warm_ocean
      frozen_peaks:
        replacement-biome: windswept_hills
      frozen_river:
        replacement-biome: river
      grove:
        replacement-biome: meadow
      ice_spikes:
        replacement-biome: windswept_hills
      jagged_peaks:
        replacement-biome: windswept_hills
      jungle:
        replacement-biome: jungle
      lukewarm_ocean:
        replacement-biome: warm_ocean
      lush_caves:
        replacement-biome: lush_caves
      meadow:
        replacement-biome: meadow
      mushroom_fields:
        replacement-biome: desert
      ocean:
        replacement-biome: warm_ocean
      old_growth_birch_forest:
        replacement-biome: old_growth_birch_forest
      old_growth_pine_taiga:
        replacement-biome: old_growth_pine_taiga
      old_growth_spruce_taiga:
        replacement-biome: old_growth_spruce_taiga
      plains:
        replacement-biome: plains
      river:
        replacement-biome: river
      savanna:
        replacement-biome: savanna
      savanna_plateau:
        replacement-biome: savanna_plateau
      snowy_beach:
        replacement-biome: desert
      snowy_plains:
        replacement-biome: plains
      snowy_slopes:
        replacement-biome: windswept_hills
      snowy_taiga:
        replacement-biome: taiga
      sparse_jungle:
        replacement-biome: sparse_jungle
      stony_peaks:
        replacement-biome: stony_peaks
      stony_shore:
        replacement-biome: desert
      sunflower_plains:
        replacement-biome: sunflower_plains
      swamp:
        replacement-biome: swamp
      taiga:
        replacement-biome: taiga
      warm_ocean:
        replacement-biome: warm_ocean
      windswept_forest:
        replacement-biome: windswept_forest
      windswept_gravelly_hills:
        replacement-biome: windswept_gravelly_hills
      windswept_hills:
        replacement-biome: windswept_hills
      windswept_savanna:
        replacement-biome: windswept_savanna
      wooded_badlands:
        replacement-biome: wooded_badlands

  # ======== BiomeRemap example: hell ================================================================
  # There will be hell to pay.
  # It is unclear what you might want to do, but MC 1.16 nether biomes are listed here for reference.
  #
  # enabled-worlds must be changed to reflect your target worlds.
  #
  hell:
    description: "There will be hell to pay."
    enabled-worlds: []
    biomes:
      basalt_deltas:
        replacement-biome: basalt_deltas
      crimson_forest:
        replacement-biome: crimson_forest
      nether_wastes:
        replacement-biome: nether_wastes
      soul_sand_valley:
        replacement-biome: soul_sand_valley
      warped_forest:
        replacement-biome: warped_forest

# ========== REPORT REMAP PROGRESS =================================================================
# How often region commands should report progress, as a percentage of completion.
# If 0, progress will not be reported.
report-region-remap-progress: 5
report-region-scan-progress: 10
