# BiomeRemap
# This file must contain valid YAML code. A YAML checker may be found at http://www.yamllint.com
#
# Remap biomes to create strange new worlds.
#
# Design: SlimeDog
# Implementation: drives_a_ford
# Testing: SlimeDog
#
# Minecraft version support:
#   BiomeRemap 1.0.1    Spigot 1.14.4     
#   BiomeRemap 2.0.3    Spigot 1.15.2     
#   BiomeRemap 2.2.1    Spigot and Paper 1.16.5     
#   BiomeRemap 2.3.1    Spigot and Paper 1.17.1
#
# ========== CAVEATS AND WARNINGS ==================================================================
# BiomeRemap is provided for your enjoyment and entertainment. We cannot guarantee that the results
# will meet your needs or desires.
#
# The most important caveat: BIOME REMAPPING CANNOT BE REVERSED. Always backup the server before
# using this plugin, and test the functionality before you use it on a production server.
#
# BiomeRemap augments terrain generation by remapping biomes in the configured worlds as chunks are
# generated. Remapping previously generated chunks carries negative performance impacts and other
# potential risks. (For example, the underlying chunk populator may change, which could result in
# mismatched chunk or biome borders.) Consequently, BiomeRemap will not remap existing chunks
# automatically, even if the configuration is changed. They can be remapped manually, if desired.
# Commands to do so are described in the wiki.
#
# Due to the way Minecraft world creation and chunk generation work, BiomeRemap cannot automatically
# remap the chunks initially-generated on world creation. These chunks must be remapped manually.
# Commands to do so are described in the wiki.
#
# Note that all 1.14/1.15/1.16/1.17 biomes are included in the configured biomemaps. These include
# dripstone_caves and lush_caves, which cannot be created on vanilla servers, but are included for
# completeness, since they are found in the 1.17 locatebiome list. We do not recommend that other
# biomes be remapped to them until 1.18. Biomes that do not exist in your Minecraft version will
# generate warnings in the console/log on plugin enable; these may be safely ignored.
#
# Changes of this magnitude should always be performed first on a test server, in order to verify
# that the configuration and results meet expectations. We strongly recommend making a server backup
# before installing and using any new plugin.

# ========== CONFIGURATION FILE VERSION ============================================================
# Do not edit the version string unless you know what you are dolng.
file: config.yml
version: 4

# ========== CHECK FOR UPDATES =====================================================================
# If you do not want notification of available updates in the console log, you may disable it here.
check-for-updates: true

# ========== BSTATS METRICS ========================================================================
# By default, the plugin collects and transmits anonymous statistics to bstats.org.
# Data collection may be disabled here, or generally in the bStats/config.yml.
#
enable-metrics: true

# ========== BIOMEMAP CONFIGURATION ================================================================
# The main configuration is a list of biomemaps, enabled in specific world(s).
# Each biomemap contains a list of assigned worlds, and a list of biomes with replacement-biomes.
#
# biomemaps:
#   NAME:
#     description: TEXT
#     enabled-worlds: LIST
#     full-chunk-remap: true|false (default:false)
#     biomes:
#        BIOME_ENUM:
#         replacement-biome: BIOME_ENUM
#
# biomemaps.NAME
#   * required, unique
#   * identifies a biomemap
#   * multiple biomemaps may be defined, and subsets of worlds assigned to them
#   * snowbound and boilerroom sample biomemaps are included in the default configuration
# biomemaps.NAME.description
#   * optional, for reference only
# biomemaps.NAME.enabled-worlds
#   * required, a list of assigned worlds
#   * a world may be assigned to more than one biomemap, if you understand the consequences
#   * may be the empty set [] if no worlds are assigned
#   * overlapping combinations of worlds and biomes will generate non-fatal warnings in the console/log
# biomemaps.NAME.full-chunk-remap
#   * Prior to MC 1.16.2, "chunk" referred to a 16x16 column, across all Y values; the biome of the
#     entire column was specified by a single BIOME_ENUM value in the base chunk (Y=0).
#   * Starting with MC 1.16.2, "chunk" refers to a 16x16x16 cube; the biome of each cubic chunk may
#     be specified independently. BiomeRemap addresses this change in the following way:
#        * biomemaps.NAME.full-chunk-remap: false (default)
#          Only the base chunk (Y=0) will be remapped. This changes weather (for example, rain vs.
#          snow) in the entire column, but changes the visual characteristics (for example, grass
#          color) in the base chunk only. So the surface terrain characteristics remain unchanged.
#        * biomemaps.NAME.full-chunk-remap: true
#          The entire column will be remapped. This changes weather in the same way, but changes the
#          the visual characteristics of the entire column, so the surface terrain characteristics
#          will reflect the new biome. This will incur a small additional computational cost to loop
#          through the entire column, but it should not be noticeable in practice, and will not affect
#          game play if the chunks are pre-generated (which we recommend in any event).
#   * WARNING: The configuration should be changed only after careful consideration and testing. The
#     consequences of TRUE cannot be reversed, except by regenerating chunks after reverting to FALSE.
# biomemaps.NAME.biomes.BIOME_ENUM
#   * Required, unique per biomemap
#   * Identifies the vanilla biome that will be replaced
#   * An invalid biome ENUM will generate a non-fatal warning in the console/log
#   * Valid biome ENUMs may be found at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html
#     but we use lowercase, which may be found at https://minecraft.gamepedia.com/Biome
#   * Biome descriptions may be found at https://minecraft.gamepedia.com/Biome
#   * Additional information may be found at https://github.com/SlimeDog/BiomeRemap/wiki/
# biomemaps.NAME.biomes.BIOME_ENUM.replacement-biome
#   * Optional
#   * If present, defines the replacement biome
#   * If replacement is not defined for any biome, the biome will not be replaced
#   * An invalid biome ENUM will generate a non-fatal warning in the console/log, and revert to the named biome
#
# Other configuration nodes may be added, as usage warrants.

biomemaps:
  # ======== BiomeRemap example: snowbound ===========================================================
  # The climate has turned very cold. The entire world is covered with ice and snow.
  # Map every biome to a colder biome.
  #
  # enabled-worlds must be changed to reflect your target worlds.
  #
  snowbound:
    description: "The world is cold and icy. Snow everywhere."
    enabled-worlds:
      - world_name_goes_here
    full-chunk-remap: false
    biomes:
      badlands:
        replacement-biome: snowy_tundra
      badlands_plateau:
        replacement-biome: snowy_tundra
      bamboo_jungle:
        replacement-biome: snowy_taiga
      bamboo_jungle_hills:
        replacement-biome: snowy_taiga_hills
      beach:
        replacement-biome: snowy_beach
      birch_forest:
        replacement-biome: snowy_tundra
      birch_forest_hills:
        replacement-biome: snowy_taiga_hills
      cold_ocean:
        replacement-biome: frozen_river
      dark_forest:
        replacement-biome: snowy_tundra
      dark_forest_hills:
        replacement-biome: snowy_taiga_hills
      deep_cold_ocean:
        replacement-biome: frozen_river
      deep_frozen_ocean:
        replacement-biome: frozen_river
      deep_lukewarm_ocean:
        replacement-biome: frozen_river
      deep_ocean:
        replacement-biome: frozen_river
      deep_warm_ocean:
        replacement-biome: frozen_river
      desert:
        replacement-biome: snowy_tundra
      desert_hills:
        replacement-biome: snowy_taiga_hills
      desert_lakes:
        replacement-biome: snowy_tundra
      dripstone_caves:
        replacement-biome: snowy_tundra
      eroded_badlands:
        replacement-biome: snowy_tundra
      flower_forest:
        replacement-biome: snowy_tundra
      forest:
        replacement-biome: snowy_tundra
      frozen_ocean:
        replacement-biome: frozen_river
      frozen_river:
        replacement-biome: frozen_river
      giant_spruce_taiga:
        replacement-biome: snowy_taiga
      giant_spruce_taiga_hills:
        replacement-biome: snowy_taiga_hills
      giant_tree_taiga:
        replacement-biome: snowy_taiga
      giant_tree_taiga_hills:
        replacement-biome: snowy_taiga_hills
      gravelly_mountains:
        replacement-biome: snowy_taiga_mountains
      ice_spikes:
        replacement-biome: ice_spikes
      jungle:
        replacement-biome: snowy_tundra
      jungle_edge:
        replacement-biome: snowy_tundra
      jungle_hills:
        replacement-biome: snowy_taiga_hills
      lukewarm_ocean:
        replacement-biome: frozen_river
      lush_caves:
        replacement-biome: snowy_tundra
      modified_badlands_plateau:
        replacement-biome: snowy_tundra
      modified_gravelly_mountains:
        replacement-biome: snowy_taiga_mountains
      modified_jungle:
        replacement-biome: snowy_tundra
      modified_jungle_edge:
        replacement-biome: snowy_tundra
      modified_wooded_badlands_plateau:
        replacement-biome: snowy_tundra
      mountain_edge:
        replacement-biome: snowy_tundra
      mountains:
        replacement-biome: snowy_taiga_mountains
      mushroom_field_shore:
        replacement-biome: snowy_beach
      mushroom_fields:
        replacement-biome: snowy_tundra
      ocean:
        replacement-biome: frozen_river
      plains:
        replacement-biome: snowy_tundra
      river:
        replacement-biome: frozen_river
      savanna:
        replacement-biome: snowy_tundra
      savanna_plateau:
        replacement-biome: snowy_tundra
      shattered_savanna:
        replacement-biome: snowy_tundra
      shattered_savanna_plateau:
        replacement-biome: snowy_tundra
      snowy_beach:
        replacement-biome: snowy_beach
      snowy_mountains:
        replacement-biome: snowy_taiga_mountains
      snowy_taiga:
        replacement-biome: snowy_taiga
      snowy_taiga_hills:
        replacement-biome: snowy_taiga_hills
      snowy_taiga_mountains:
        replacement-biome: snowy_taiga_mountains
      snowy_tundra:
        replacement-biome: snowy_tundra
      stone_shore:
        replacement-biome: snowy_beach
      sunflower_plains:
        replacement-biome: snowy_tundra
      swamp:
        replacement-biome: snowy_tundra
      swamp_hills:
        replacement-biome: snowy_taiga_hills
      taiga:
        replacement-biome: snowy_tundra
      taiga_hills:
        replacement-biome: snowy_taiga_hills
      taiga_mountains:
        replacement-biome: snowy_taiga_mountains
      tall_birch_forest:
        replacement-biome: snowy_tundra
      tall_birch_hills:
        replacement-biome: snowy_taiga_hills
      warm_ocean:
        replacement-biome: frozen_river
      wooded_badlands_plateau:
        replacement-biome: snowy_tundra
      wooded_hills:
        replacement-biome: snowy_taiga_hills
      wooded_mountains:
        replacement-biome: snowy_taiga_mountains

  # ======== BiomeRemap example: boilerroom ==========================================================
  # Climate change is real. The entire world is warm, warmer, hot, hotter.
  # Map every biome to a warmer biome.
  #
  # enabled-worlds must be changed to reflect your target worlds.
  #
  boilerroom:
    description: "Climate change is real. The entire world is warm, warmer, hot, hotter."
    enabled-worlds: []
    full-chunk-remap: false
    biomes:
      badlands:
        replacement-biome: badlands
      badlands_plateau:
        replacement-biome: badlands_plateau
      bamboo_jungle:
        replacement-biome: bamboo_jungle
      bamboo_jungle_hills:
        replacement-biome: bamboo_jungle_hills
      beach:
        replacement-biome: desert
      birch_forest:
        replacement-biome: birch_forest
      birch_forest_hills:
        replacement-biome: birch_forest_hills
      cold_ocean:
        replacement-biome: warm_ocean
      dark_forest:
        replacement-biome: dark_forest
      dark_forest_hills:
        replacement-biome: dark_forest_hills
      deep_cold_ocean:
        replacement-biome: deep_lukewarm_ocean
      deep_frozen_ocean:
        replacement-biome: deep_lukewarm_ocean
      deep_lukewarm_ocean:
        replacement-biome: deep_lukewarm_ocean
      deep_ocean:
        replacement-biome: deep_lukewarm_ocean
      deep_warm_ocean:
        replacement-biome: deep_warm_ocean
      desert:
        replacement-biome: desert
      desert_hills:
        replacement-biome: desert_hills
      desert_lakes:
        replacement-biome: desert_lakes
      dripstone_caves:
        replacement-biome: dripstone_caves
      eroded_badlands:
        replacement-biome: eroded_badlands
      flower_forest:
        replacement-biome: flower_forest
      forest:
        replacement-biome: forest
      frozen_ocean:
        replacement-biome: warm_ocean
      frozen_river:
        replacement-biome: river
      giant_spruce_taiga:
        replacement-biome: giant_spruce_taiga
      giant_spruce_taiga_hills:
        replacement-biome: giant_spruce_taiga_hills
      giant_tree_taiga:
        replacement-biome: giant_tree_taiga
      giant_tree_taiga_hills:
        replacement-biome: giant_tree_taiga_hills
      gravelly_mountains:
        replacement-biome: gravelly_mountains
      ice_spikes:
        replacement-biome: mountains
      jungle:
        replacement-biome: jungle
      jungle_edge:
        replacement-biome: jungle_edge
      jungle_hills:
        replacement-biome: jungle_hills
      lukewarm_ocean:
        replacement-biome: warm_ocean
      lush_caves:
        replacement-biome: lush_caves
      modified_badlands_plateau:
        replacement-biome: modified_badlands_plateau
      modified_gravelly_mountains:
        replacement-biome: modified_gravelly_mountains
      modified_jungle:
        replacement-biome: modified_jungle
      modified_jungle_edge:
        replacement-biome: modified_jungle_edge
      modified_wooded_badlands_plateau:
        replacement-biome: modified_wooded_badlands_plateau
      mountain_edge:
        replacement-biome: mountain_edge
      mountains:
        replacement-biome: mountains
      mushroom_field_shore:
        replacement-biome: desert
      mushroom_fields:
        replacement-biome: desert
      ocean:
        replacement-biome: warm_ocean
      plains:
        replacement-biome: plains
      river:
        replacement-biome: river
      savanna:
        replacement-biome: savanna
      savanna_plateau:
        replacement-biome: savanna_plateau
      shattered_savanna:
        replacement-biome: shattered_savanna
      shattered_savanna_plateau:
        replacement-biome: shattered_savanna_plateau
      snowy_beach:
        replacement-biome: desert
      snowy_mountains:
        replacement-biome: mountains
      snowy_taiga:
        replacement-biome: taiga
      snowy_taiga_hills:
        replacement-biome: taiga_hills
      snowy_taiga_mountains:
        replacement-biome: taiga_mountains
      snowy_tundra:
        replacement-biome: plains
      stone_shore:
        replacement-biome: desert
      sunflower_plains:
        replacement-biome: sunflower_plains
      swamp:
        replacement-biome: swamp
      swamp_hills:
        replacement-biome: swamp_hills
      taiga:
        replacement-biome: taiga
      taiga_hills:
        replacement-biome: taiga_hills
      taiga_mountains:
        replacement-biome: taiga_mountains
      tall_birch_forest:
        replacement-biome: tall_birch_forest
      tall_birch_hills:
        replacement-biome: tall_birch_hills
      warm_ocean:
        replacement-biome: warm_ocean
      wooded_badlands_plateau:
        replacement-biome: wooded_badlands_plateau
      wooded_hills:
        replacement-biome: wooded_hills
      wooded_mountains:
        replacement-biome: wooded_mountains

  # ======== BiomeRemap example: hell ================================================================
  # There will be hell to pay.
  # It is unclear what you might want to do, but MC 1.16 nether biomes are listed here for reference.
  #
  # enabled-worlds must be changed to reflect your target worlds.
  #
  hell:
    description: "There will be hell to pay."
    enabled-worlds: []
    full-chunk-remap: false
    biomes:
      basalt_deltas:
        replacement-biome: basalt_deltas
      crimson_forest:
        replacement-biome: crimson_forest
      nether_wastes:
        replacement-biome: nether_wastes
      soul_sand_valley:
        replacement-biome: soul_sand_valley
      warped_forest:
        replacement-biome: warped_forest

# ========== REPORT REMAP PROGRESS =================================================================
# How often region commands should report progress, as a percentage of completion.
# If 0, progress will not be reported.
report-region-remap-progress: 5
report-region-scan-progress: 10
